### ISSUE TITLE
EPEL for Centos 7 GPG key missing

### ISSUE THREAD

**Issue by goetzk** [example42/puppet-yum#103]
EPEL key for Centos 7 is missing from the puppet-yum module.
```
Error: /Stage[main]/Yum::Repo::Epel/Yum::Managed_yumrepo[epel]/File[/etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-7]: Could not evaluate: Could not retrieve information from environment production source(s) puppet:///modules/yum/rpm-gpg/RPM-GPG-KEY-EPEL-7
```
After I added the key from epel-release to my copy of puppet-yum and it started to work as expected.

**Comment by alvagante** [comment]
You are probably using an old version of the module (did you download it from the forge?)
The file is there: https://github.com/example42/puppet-yum/blob/master/files/rpm-gpg/RPM-GPG-KEY-EPEL-7

**Comment by alvagante** [comment]
FYI, just uploaded on the forge the latest version on this module, there there's the missing file

**Comment by goetzk** [comment]
Thanks for looking in to this.
