### ISSUE TITLE
Puppet 4 compability

### ISSUE THREAD

**Issue by reupke** [example42/puppet-yum#108]
I have used this module previously with success, but with Puppet 4 it's failing.

Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Evaluation Error: Error while evaluating a Function Call, hiera() has been converted to 4x API at /etc/puppetlabs/code/environments/production/modules/yum/manifests/init.pp:167:26 on node puppet

Is this a known issue and how can it be fixed?

**Comment by alvagante** [comment]
It's a know issue of puppi's params_lookup compatibility with Puppet4.
The ticket of reference is this one https://github.com/example42/puppi/issues/123

**Comment by davividal** [comment]
I'm using this module with Puppet 4.5 and I saw no issues. Is this ticket still relevant?

**Comment by alvagante** [comment]
Actually this has been solved. Thanks for the notice.
