### ISSUE TITLE
metadata.json file permissions are "600"

### ISSUE THREAD

**Issue by mpdude** [example42/puppet-yum#131]
Hi there,

I am using `librarian-puppet` to install some modules and puppet-yum gets downloaded as a dependency.

The `metadata.json` file in the module's directory ends up with `0600` file permissions. For some reason, the puppet master tries to read this file and fails.

Other modules I am using do not show this problem.

Any idea what might be wrong?

**Comment by alvagante** [comment]
Uhm, I've tried to install the yum module from the forge and I see 640 permissions. I pushed anyway a new version, could you verify if you still have issues with the latest version?

**Comment by mpdude** [comment]
:+1: it works now, thanks a lot!
