### ISSUE TITLE
Wrong file permissions on some file breaks Foreman import

### ISSUE THREAD

**Issue by clauded** [example42/puppet-yum#135]
We use r10k v2.0.3 to deploy your module directly from the github repository (essentially, it's doing a git clone). Some of the files recently updated miss the everyone read access:

root@puppet:/etc/puppet/environments/developpement/modules/yum/manifests# ll
total 64
drwxr-xr-x 4 root root  4096 Oct 15 15:36 ./
drwxr-xr-x 6 root root  4096 Oct 15 15:36 ../
-rw-r--r-- 1 root root  1033 Oct 15 15:36 cron.pp
-rw-r----- 1 root root  3060 Oct 15 15:36 defaults.pp
-rw-r----- 1 root root 12844 Oct 15 15:36 init.pp
-rw-r--r-- 1 root root  2403 Oct 15 15:36 managed_yumrepo.pp
-rw-r----- 1 root root  1759 Oct 15 15:36 params.pp
drwxr-xr-x 2 root root  4096 Oct 15 15:36 plugin/
-rw-r--r-- 1 root root  1096 Oct 15 15:36 plugin.pp
-rw-r--r-- 1 root root   508 Oct 15 15:36 prerequisites.pp
drwxr-xr-x 2 root root  4096 Oct 15 15:36 repo/
-rw-r--r-- 1 root root  1085 Oct 15 15:36 updatesd.pp
-rw-r--r-- 1 root root   568 Oct 15 15:36 versionlock.pp

We use Foreman as an ENC and when we try to import the classes, we get a 406 error from foreman-proxy as the proxy is trying to read the files but doesn't have access. If we manually set file permission to 644, foreman-proxy completes successfully.

Can you please fix file permissions on these files  in manifests and manifests/repo?

**Comment by alvagante** [comment]
New version v2.1.25 should fix it, pls let me know...

**Comment by clauded** [comment]
It's fixed. Thanks!
