### ISSUE TITLE
Cron. Install security updates.

### ISSUE THREAD

**Issue by username1366** [example42/puppet-yum#143]
When I enable automatic updates:

        class { 'yum':
          update => 'cron',
          cron_update_cmd => 'minimal',
        }

I get an error:

Error: Evaluation Error: Error while evaluating a Function Call, Could not find class ::cron for localhost at /tmp/vagrant-puppet/modules-fa145af311a62d91c3c7de21318594ae/yum/manifests/init.pp:353:5 on node localhost

**Comment by 5obol** [comment]
Same issue here.

**Comment by alvagante** [comment]
Check the referenced commit, it should fix the issue (for Puppet 4 )

**Comment by 5obol** [comment]
That works brilliantly, any chance of pushing this to forge version?

**Comment by alvagante** [comment]
Just pushed version 2.1.16with current master. thx
