### ISSUE TITLE
Add support for OEL 7

### ISSUE THREAD

**Issue by felipe1982** [example42/puppet-yum#152]
http://public-yum.oracle.com/getting-started.html

```
Oracle Linux 7
# cd /etc/yum.repos.d
# wget http://yum.oracle.com/public-yum-ol7.repo
```

Key: http://public-yum.oracle.com/RPM-GPG-KEY-oracle-ol7

More Info (keys): https://docs.oracle.com/cd/E37670_01/E39381/html/ol_import_gpg.html

**Comment by alvagante** [comment]
PR welcomed
