### ISSUE TITLE
cyclic dependency 

### ISSUE THREAD

**Issue by FrankVanDamme** [example42/puppet-yum#166]
Since 60e79178a5298c21d38ae3b424e0534f810ede67, a Puppet run on a CentOS 6 box (simply including the "yum" class) produces this error: 

Error: Failed to apply catalog: Found 1 dependency cycle:
(Package[yum-plugin-priorities] => Yum::Plugin[priorities] => Class[Yum::Prerequisites] => Yum::Managed_yumrepo[epel] => Class[Yum::Repo::Epel] => Class[Yum::Defaults] => Class[Yum] => Class[Yum::Prerequisites] => Yum::Plugin[priorities] => Package[yum-plugin-priorities])
Try the '--graph' option and opening the resulting '.dot' file in OmniGraffle or GraphViz

## Specifications

Please add this info:

  1. Output of ```facter -p``` on the failing node (at least the OS related facts)

operatingsystem => CentOS
operatingsystemmajrelease => 6
operatingsystemrelease => 6.6
os => {"name"=>"CentOS", "lsb"=>{"distrelease"=>"6.6", "distdescription"=>"CentOS release 6.6 (Final)", "distcodename"=>"Final", "majdistrelease"=>"6", "distid"=>"CentOS", "minordistrelease"=>"6", "release"=>":base-4.0-ia32:base-4.0-noarch:core-4.0-ia32:core-4.0-noarch:graphics-4.0-ia32:graphics-4.0-noarch:printing-4.0-ia32:printing-4.0-noarch"}, "family"=>"RedHat", "release"=>{"minor"=>"6", "full"=>"6.6", "major"=>"6"}}
osfamily => RedHat
osplatform => el6
partitions => {"sda1"=>{"mount"=>"/boot", "filesystem"=>"ext4", "uuid"=>"1bd437a3-d805-4a2f-9df2-81ecbe50915d", "size"=>"1024000"}, "sda2"=>{"filesystem"=>"LVM2_member", "size"=>"15751168"}}
path => /usr/lib/qt-3.3/bin:/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin:/root/bin
physicalprocessorcount => 1
processor0 => Intel(R) Core(TM) i5-5300U CPU @ 2.30GHz
processorcount => 1
processors => {"count"=>1, "physicalcount"=>1, "models"=>["Intel(R) Core(TM) i5-5300U CPU @ 2.30GHz"]}
productname => VirtualBox
ps => ps -ef
puppet_vardir => /var/lib/puppet
puppetversion => 3.8.3
root_home => /root
rubyplatform => i386-linux
rubysitedir => /usr/lib/ruby/site_ruby/1.8
rubyversion => 1.8.7
selinux => true
selinux_config_mode => enforcing
selinux_config_policy => targeted
selinux_current_mode => enforcing
selinux_enforced => true
selinux_policyversion => 24
serialnumber => 0

  1. Version of Puppet and of the module

[root@prettysix ~]# puppet --version
3.8.3

Master:
$  dpkg -l | grep pup
ii  facter                                   2.4.6-1puppetlabs1        all                       Ruby module for collecting simple facts about a host operating system
ii  hiera                                    1.3.4-1puppetlabs1        all                       A simple pluggable Hierarchical Database.
ii  mcollective-common                       2.8.4-1puppetlabs1        all                       build server orchestration or parallel job execution systems
rc  puppet                                   3.6.2-1puppetlabs1        all                       Centralized configuration management - agent startup and compatibility scripts
ii  puppet-common                            3.8.7-1puppetlabs1        all                       Centralized configuration management
ii  puppet-dashboard                         1.2.23-1puppetlabs1       all                       Dashboard for Puppet
ii  puppetlabs-release                       1.1-1                     all                       "Package to install Puppet Labs gpg key and apt repo"
rc  puppetmaster                             2.7.23-1~deb7u3           all                       Centralized configuration management - master startup and compatibility scripts
ii  puppetmaster-common                      3.8.7-1puppetlabs1        all                       Puppet master common scripts
ii  puppetmaster-passenger                   3.8.7-1puppetlabs1        all                       Centralised configuration management - master setup to run under mod passenger
ii  ruby-rgen                                0.6.5-1puppetlabs1        all                       A framework supporting Model Driven Software Development (MDSD)
ii  ruby-stomp                               1.3.2-1puppetlabs1        all                       A ruby client for sending and receiving messages
ii  vim-puppet                               3.8.7-1puppetlabs1        all                       syntax highlighting for puppet manifests in vim

**Comment by alvagante** [comment]
Thanks for the report!
