### ISSUE TITLE
Add support for Remi PHP 7.1 repo

### ISSUE THREAD

**Issue by dstepe** [example42/puppet-yum#169]
The Remi repo for PHP 7.1 is available and appears to be easily added by duplicating the yum::repo::remi_php70 class.

**Comment by EdwinHoksberg** [comment]
@alvagante I saw you merged this change, could you please create a new tag so I can use it in my Puppetfile?

**Comment by alvagante** [comment]
Sure, sorry. Tag 2.1.28 just published here and on the forge.
