### ISSUE TITLE
Error: Evaluation Error: Unknown function: 'any2bool'. at init.pp:213:26

### ISSUE THREAD

**Issue by jengstrom** [example42/puppet-yum#177]
Puppet agent -t returns the following even though puppetlabs/stdlib is in module path.

"Error: Evaluation Error: Unknown function: 'any2bool'. at init.pp:213:26"

puppet --version
4.5.2

mod 'example42/yum',
  :git => 'https://github.com/example42/puppet-yum.git',
  :ref => 'v2.1.28'

**Comment by alvagante** [comment]
As a reference:
the function any2bool is provided by a recent version of stdlib:
https://github.com/puppetlabs/puppetlabs-stdlib#any2bool
Before being added to stdlib we used to have it in puppi (https://github.com/example42/puppi/commit/db0aac5ce2fd3d031011e09de6d74ac897a01222)
