### ISSUE TITLE
cron updates?

### ISSUE THREAD

**Issue by salderma** [example42/puppet-yum#31]
README says:

class { 'yum':
  update => 'cron',
}

This appears to initiate no changes in puppet ?  I was expecting a script added to cron.<timeframe> or crontab, but no changes.  I also notice in init.pp the param is there but there is no action taken based on the value/presence of the param.

What's required to make this feature work?

**Comment by shellfu** [comment]
Closing Issue. Pull request was merged on Feb 2, 2014
