### ISSUE TITLE
"options" feature is not working

### ISSUE THREAD

**Issue by nixmore** [example42/puppet-yum#51]
Hey, thanks for this awesome module, I use it on all of my EL-based machines.

I recently had a need to exclude a package via yum configs, so I tried using `yum::options` but I can't get it to work. I tried looking through your code to figure it out but ultimately ended up here to ask you for your help.

This is my hiera code:
```
---
classes:
 - yum

yum::options:
 - "exclude=cloud-init"
```

**Comment by shellfu** [comment]
Closing this as it's a non-issue.
