### ISSUE TITLE
Epel fails to install on CentOS 7

### ISSUE THREAD

**Issue by Yuav** [example42/puppet-yum#62]
Error: /Stage[main]/Yum::Repo::Epel/Yum::Managed_yumrepo[epel]/File[/etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-7]: Could not evaluate: Could not retrieve information from environment production source(s) puppet:///modules/yum/rpm-gpg/RPM-GPG-KEY-EPEL-7
Notice: /Stage[main]/Yum::Repo::Epel/Yum::Managed_yumrepo[epel]/File[/etc/yum.repos.d/epel.repo]/ensure: created
Notice: /Stage[main]/Yum::Repo::Epel/Yum::Managed_yumrepo[epel]/Yumrepo[epel]: Dependency File[/etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-7] has failures: true
Warning: /Stage[main]/Yum::Repo::Epel/Yum::Managed_yumrepo[epel]/Yumrepo[epel]: Skipping because of failed dependencies

**Comment by shellfu** [comment]
We are currently working on more OS coverage for all example42 modules. Currently as the module stands, it does not support RHEL7 variants.  However, this should be trivial to add, and I will take a look at this early next week.

**Comment by JosephMaxwell** [comment]
Any update on this? I am running into the same issue.

**Comment by shellfu** [comment]
Not yet. I need to circle back around to this problem. I have been working on fixing some of the other issues before adding more coverage, but I myself am starting to deploy RHEL7 variants, and understand this is high priority for some folks.

**Comment by JosephMaxwell** [comment]
No problem. I am just grateful for your development on this. Thank you.

**Comment by shellfu** [comment]
Looks like RPM-GPG-KEY-EPEL-7 was added by Al 7 months ago. This should no longer be an issue, and I have just tested on a fresh CentOS 7 install this afternoon.
